imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

services:
    test_AppBundle\Service\RegistrationEmail:
        alias: 'AppBundle\Service\RegistrationEmail'
        public: true

    test_AppBundle\Service\EmailMessageFactory:
        alias: 'AppBundle\Service\EmailMessageFactory'
        public: true

doctrine:
    dbal:
        driver: pdo_mysql
        server_version: 5.6
        host: '%test_database_host%'
        port: '%test_database_port%'
        dbname: '%test_database_name%'
        user: '%test_database_user%'
        password: '%test_database_password%'
        charset: UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
